import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
            <ClerkProvider>
        <html lang="en">
                <body className={`${inter.className} bg-light-1 text-dark-1`}>
                    {children}
                </body>
        </html>
            </ClerkProvider>
    );
}
